In [1]:
%pip install numpy 
import numpy as np


[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
#array creation 
#default values 
zeros = np.zeros((2,3))
ones = np.ones((2,3))
full = np.full((2,3), 7)
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Full:\n", full)

#squences 
arr = np.arange(1,10,3)
print("Arange:\n", arr)

#identity matrix
identity = np.eye(3)
print("Identity Matrix:\n", identity)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]]
Arange:
 [1 4 7]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#aggregationc functions 

sid = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Sum:", np.sum(sid))
print("Mean:", np.mean(sid))
print("Max:", np.max(sid))      
print("Min:", np.min(sid))
print("Standard Deviation:", np.std(sid))
print("Variance:", np.var(sid))
print("Median:", np.median(sid))
print("Unique:", np.unique(sid))


Sum: 45
Mean: 5.0
Max: 9
Min: 1
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667
Median: 5.0
Unique: [1 2 3 4 5 6 7 8 9]


In [ ]:
#fancy indexing : selectin mutliple elements in array 
print("Fancy Indexing:")
sid = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(sid[[0,1], [1,2]])  # selects elements at (0,1) and (1,2)

#boolean indexing : select elements based on condition
print("Boolean Indexing:")
print(sid[sid > 5])  # selects elements greater than 5

Fancy Indexing:
[2 6]


In [ ]:
#reshaping and manipulating arrays 
"""Reshaping doesn't create a copy it returns a view of the original array with a new shape.
If you modify the reshaped array, it will affect the original array since they share the same data in memory. However, if you use the reshape method with the order parameter set to 'C' (row-major order) or 'F' (column-major order), it may create a copy of the data, and modifications to the reshaped array will not affect the original array.
"""

print(sid.shape)  # original shape
reshaped = sid.reshape(1,9)  # reshape to 1 row and 9 columns
print("Reshaped Array:\n", reshaped)
print("Original Array after reshaping:\n", sid)  # original array remains unchanged

print(sid.ravel())
print(sid.flatten())
#difference between ravel and flatten is that ravel returns a view of the original array whenever possible, while flatten always returns a copy. Therefore, modifications to the array returned by ravel may affect the original array, while modifications to the array returned by flatten will not affect the original array.


(3, 3)
Reshaped Array:
 [[1 2 3 4 5 6 7 8 9]]
Original Array after reshaping:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#advacned numpy
"""
insert, delete, append, concatenate, stack, split, tile, repeat

insert: inserts values into an array at specified indices.
delete: removes elements from an array at specified indices.
append: adds values to the end of an array.
concatenate: joins two or more arrays along an existing axis.
stack: joins arrays along a new axis.
split: splits an array into multiple sub-arrays along an existing axis.
tile: repeats an array a specified number of times.
repeat: repeats elements of an array a specified number of times.
extend: extends an array by appending elements from another array."""

insert_arr = np.insert(sid,5,99)  # insert 99 at index 5
print("After Insertion:\n", insert_arr)

#inserting in  multidimensional array
insert_arr_2d = np.insert(sid, 1, [99, 88, 77], axis=0)  # insert a new row at index 1